# Generated by Django 4.2 on 2023-04-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('validade', models.DateField()),
                ('marca', models.CharField(max_length=200)),
                ('armazenamento', models.CharField(choices=[('aberto', 'aberto'), ('estoque', 'estoque')], max_length=10)),
                ('situacao', models.CharField(choices=[('Acabando', 'Acambando'), ('Acabou', 'Acabou'), ('Cheio', 'Cheio')], max_length=20)),
            ],
        ),
    ]
