# Generated by Django 4.2 on 2023-06-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='armazenamento',
        ),
        migrations.AddField(
            model_name='produto',
            name='aberto',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='fechado',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
